version: '3.1'
services:
  spring-eureka-1:
    restart: always
    image: 172.26.0.52:5000/spring-cloud-eureka
    container_name: spring-eureka-1
    ports:
      - 8761:8761
    networks:
      - eureka-network

  spring-eureka-2:
    restart: always
    image: 172.26.0.52:5000/spring-cloud-eureka
    container_name: spring-eureka-2
    ports:
      - 8861:8761
    networks:
      - eureka-network

  spring-eureka-3:
    restart: always
    image: 172.26.0.52:5000/spring-cloud-eureka
    container_name: spring-eureka-3
    ports:
      - 8961:8761
    networks:
      - eureka-network

networks:
  eureka-network: