stages:
  - build
  - push
  - run
  - clean

build:
  stage: build
  script:
    - mvn clean package
    - cp target/hello-spring-cloud-zipkin-1.0.0-SNAPSHOT.jar docker
    - cd docker/
    - docker build -t 172.26.0.52:5000/spring-cloud-zipkin .

push:
  stage: push
  script:
    - docker push 172.26.0.52:5000/spring-cloud-zipkin

run:
  stage: run
  script:
    - cd docker
    - docker-compose down
    - docker-compose up -d

clean:
  stage: clean
  script:
    - docker rmi $(docker images -q -f dangling=true)
