spring:
  application:
    name: hello-spring-cloud-eureka
  zipkin:
    base-url: http://172.26.0.51:9411
  boot:
    admin:
      client:
        url: http://172.26.0.51:8084

server:
  port: 8761

eureka:
  instance:
    hostname: host
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.26.0.51:8761/eureka/,http://172.26.0.51:8861/eureka/,http://172.26.0.51:8961/eureka/