spring:
  application:
    name: hello-spring-cloud-zipkin
  boot:
    admin:
      client:
        url: http://172.26.0.51:8084

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.26.0.51:8761/eureka/,http://172.26.0.51:8861/eureka/,http://172.26.0.51:8961/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
